# Generated by Django 5.0.5 on 2024-09-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='currentBalance',
            new_name='endingBalance',
        ),
    ]
